### ISSUE TITLE
Display some data registered on Med page  to Top & Asthma-attack Tracker

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#104]
Top & Ashma attack Trackers exist to track if patients are actually taking meds & what meds they are taking.

If Patients register 3 meds as regular meds + 2 meds as emergency meds on medicine note,
On top tracker, there should be 3 check lists and 2 toggle buttons on asthma-attack tracker.

### Top tracker
Data source:
<img width="1337" alt="スクリーンショット 2021-04-28 21 42 08" src="https://user-images.githubusercontent.com/61481039/116405694-e19b8e80-a86a-11eb-81ec-598c0f593d79.png">

Where to display on:
<img width="603" alt="スクリーンショット 2021-04-28 21 42 27" src="https://user-images.githubusercontent.com/61481039/116407695-fda02f80-a86c-11eb-8ef4-31ae52226200.png">

**When dosage is 吸入**
- Name 
- Number of inhalation
- Number a day

**When dosage is not 吸入**
- Name 
- Number of dose
- Number a day
<br>
<br>

### Asthma Attack tracker

Data source:
<img width="1337" alt="スクリーンショット 2021-04-28 21 42 08" src="https://user-images.githubusercontent.com/61481039/116407039-4a373b00-a86c-11eb-8547-2cca553050c6.png">

Where to display on:
Regardless dosage, only Name is ok.
<img width="597" alt="スクリーンショット 2021-04-28 21 52 09" src="https://user-images.githubusercontent.com/61481039/116406875-1a883300-a86c-11eb-907c-ae78ba0561e2.png">

**Comment by Show-M** [comment]
ref #73

**Comment by sarikabhimre18** [comment]
@Show-M 
for Asthma Attack tracker
There should be display the medicine name and dosage name after the below have toggle button.That toggle button is used the above described tracker ?

For e.g in asthma attack medicine user added 3 medicine in it.
1)Step 1: Display the name of medicine and dosage 
2)Step 2: Display the toggle button from above described for each one right ?

**Comment by sarikabhimre18** [comment]
@rgagne
Questions:-
-)Is there any way to passed datasource related to particular thing in tracker form ?
For example i need to passed regular med data in the check-list metric or i need to create different metric for that so user can dispatch it.?

**Comment by Show-M** [comment]
@sarikabhimre18 

Right. 
if a user added 3 meds on Medicine page, 
When the user open up Asthma-attack tracer, those 3 meds should be displayed there. 

In this way, user can report which meds they used to ease asthma-attack.

**Comment by rgagne** [comment]
To enable this we need to add some features:

1. Dispatch query to retrieve existing list
2. Map controls onto the query results

**Comment by sarikabhimre18** [comment]
> To enable this we need to add some features:
> 
> 1. Dispatch query to retrieve existing list
> 2. Map controls onto the query results

@rgagne 
Question :-
1) We want to repeat metric[check-list] with each query list and when user dispatch from the tracker form it will able to track in which timing medicine should be taken ?.Is this change in check-list metric or made a new one ?

**Comment by Show-M** [comment]
any update on this? @sarikabhimre18

**Comment by sarikabhimre18** [comment]
@Show-M Will take a look as in the middle of something !

**Comment by Show-M** [comment]
@sarikabhimre18  any update?

**Comment by Show-M** [comment]
@rgagne 
Top-tracker is done.
Asthma-attack tracker is not implemented yet...

**Comment by Show-M** [comment]
<img width="1291" alt="スクリーンショット 2021-05-21 15 51 59" src="https://user-images.githubusercontent.com/61481039/119094837-7f3e4400-ba4c-11eb-97f5-a7c77a510d92.png">
