### ISSUE TITLE
New feature called "sentence"

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#106]
for each of 3 blanks users need to fill in the answer. 
`吸入薬：　　　　　を1回。　　　吸入を1日　　　回。
`so that, after submission, dispatch will look like a single sentence.

Location to create:
<img width="1002" alt="スクリーンショット 2021-04-16 0 44 04" src="https://user-images.githubusercontent.com/61481039/114898284-ea449b80-9e4c-11eb-80c6-d087f2e57dfc.png">

e.g
<img width="907" alt="スクリーンショット 2021-04-16 0 43 36" src="https://user-images.githubusercontent.com/61481039/114898144-d305ae00-9e4c-11eb-9a33-6850550d6da7.png">

**Comment by rgagne** [comment]
not doing
