### ISSUE TITLE
CHANT-Typing code is bugging on Join code screen

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#117]
If i type "A, B, C, D", the system make input of "A", "AB", "ABC", "ABCD"
But this happens only with 12 key..
<img width="305" alt="スクリーンショット 2021-05-20 22 02 03" src="https://user-images.githubusercontent.com/61481039/118983551-85361580-b9b7-11eb-862a-69899208672e.png">

![1](https://user-images.githubusercontent.com/61481039/118982516-7733c500-b9b6-11eb-81f3-d8f25c64f8a4.gif)

If you wanna see better
[RPReplay_Final1621515350.MP4.zip](https://github.com/weaveio/forum/files/6516033/RPReplay_Final1621515350.MP4.zip)

**Comment by rgagne** [comment]
Because that keyboard lets you keep tapping the same key and change the letter; e.g. a->b->c->a ... still one letter. We make all the letters upper case which seems to mess with it. Will figure something out.

**Comment by Show-M** [comment]
fixation is confirmed.
