### ISSUE TITLE
CHANT - After typing in join code and confirm it keeps the user in registration process loop

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#118]
After click "確認する(confirm)",  It goes back the the screen saying "コードを入力する(type in code)

What I noticed is:
1. Once I type and confirm the join code, I am in the proper group in the system(checked in admin). 
2. On top-right menu "your org" with Asthma appears only if i close the app and start again. Then i can go to Asthma org.
3. After finishing the registration process, Only if i close the app and open, i can go to Asthma org.
![IMG_0286](https://user-images.githubusercontent.com/61481039/118984877-ea3e3b00-b9b8-11eb-86de-5ad354d31c89.PNG)
![IMG_0285](https://user-images.githubusercontent.com/61481039/118984882-ead6d180-b9b8-11eb-85a9-c9ba6d2b61a8.PNG)

**Comment by Show-M** [comment]
I just tried out again on the latest build, 3.0.2613...the bug is not happening anymore  :)

**Comment by rgagne** [comment]
probably first time users; will test it out

**Comment by Show-M** [comment]
FYI I did not face this issue when i created a new account today.
