### ISSUE TITLE
Alarm clock is not triggering an action

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#123]
I can make entries.
But the alarm does not get triggered on manually set-time.

P.S notification is allowed on the phone for CHANT.
![IMG_69AE34153658-1](https://user-images.githubusercontent.com/61481039/119437175-89b45280-bd58-11eb-8125-a4210a6fff03.jpeg)

**Comment by rgagne** [comment]
Why are the entries questions?

**Comment by Show-M** [comment]
they are all reminder, just a question stype.
- Did you take meds?
- Arent you forgetting smth? 
- Did you add today note? 
- etc
they are from here. https://github.com/weaveio/forum/issues/93#issue-841607078

**Comment by rgagne** [comment]
Tested notifications and they seem to be working properly.

**Comment by Show-M** [comment]
ok.
