### ISSUE TITLE
Cannot connect to App Store

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#129]
![IMG_0310](https://user-images.githubusercontent.com/61481039/119921210-9202cc80-bfa8-11eb-89b6-732701a1c18a.PNG)
![IMG_0311](https://user-images.githubusercontent.com/61481039/119921214-93cc9000-bfa8-11eb-80d8-1f2f534a6eea.PNG)

**Comment by rgagne** [comment]
Duplicate https://github.com/weaveio/WOLL-General-forum/issues/134
