### ISSUE TITLE
"Cannot connect to App store" message when users tap "check update" on Chant app

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#134]
![IMG_0323](https://user-images.githubusercontent.com/61481039/120099784-61718d00-c178-11eb-99b8-3fe6e38e344b.PNG)
![IMG_0324](https://user-images.githubusercontent.com/61481039/120099788-659daa80-c178-11eb-8af8-ae91fd93cb28.PNG)

**Comment by rgagne** [comment]
Should be fixed in the next build; wrong id is configured. In the mean time users need to visit the app store manually.

**Comment by Show-M** [comment]
it is fixed.
