### ISSUE TITLE
Question: Educational material filled by a patient and used as a guideline(action-plan sheet)

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#61]
Doc:  
Action Plan[.docx](https://github.com/weaveio/forum/files/6062134/Action.Plan.docx)

Everytime patients get asthma-attacks, they will use this sheet as a guideline of what-to-do.

Right column is filled by patient together with doctors when they meet for the first time.
Later whenever patients get asthma-attacks, they use this right column to see what actions to take.

Left column is to check what level of asthma-attack  you are having.

Therefore once filled, it will be used as a guideline book.

- There are 4 levels of approach(Green/yellow/orange/red)
- Left column and right column will not be displayed horizontally but vertically. That is ok.
-  It says "Please create as check-box for □." Check-box will be used when Dr and patients fill in the sheet together. 
They will choose few check-box out of all for each level. After registration, only ones with check-boxed filled will be displayed.

- On the left there are part written as below on each level.  It will be 1 highest peakflow of all time users recorded. 

```
 ●ピークフローの値：
________～_______　

```
<img width="1414" alt="スクリーンショット 2021-04-14 22 24 43" src="https://user-images.githubusercontent.com/61481039/114717727-4be30800-9d70-11eb-809b-9075a247e711.png">

**Comment by Show-M** [comment]
Any suggestions where to build it and connect to wiki later?

**Comment by Show-M** [comment]
Any thoughts on this?

**Comment by Show-M** [comment]
Question to Dr: 
1. How do we calculate the value? Whats the formula?
```
 ●ピークフローの値：
________～_______　

```

2. Ieft column and right column will not be displayed horizontally but vertically. Is that ok? 
3. 

Question to Rob:
1. Can we have colored lines / background-color?
2. I dont think we can have questions like below. Therefore we need to add metrtix for each blank?
`□吸入薬：　　　　　を1回　　　吸入を1日　　　回。
`

**Comment by rgagne** [comment]
Background color yes, lines.. don't think so but could add

There is a metric called measure that let's you put some notation in the field. You can try that. Otherwise will need to make a new feature (maybe called sentence) that supports something like the above.

**Comment by Show-M** [comment]
ok, then this new type of metrix would be useful to have... #106

**Comment by Show-M** [comment]
How can we display texts with bullet point on tracker?
<img width="600" alt="スクリーンショット 2021-04-19 14 44 56" src="https://user-images.githubusercontent.com/61481039/115187244-f31fc080-a11d-11eb-90fb-bdc94edc8c80.png">
<img width="296" alt="スクリーンショット 2021-04-19 14 45 16" src="https://user-images.githubusercontent.com/61481039/115187258-f61ab100-a11d-11eb-9f27-094a9b508771.png">

**Comment by rgagne** [comment]
Completed

## Entry
![Screenshot from 2021-05-27 09-25-59](https://user-images.githubusercontent.com/428897/119747385-98704600-becd-11eb-8bbf-912aeeb15500.png)

## View
![localhost_3000_(iPhone X) - 2021-05-27T092505 616](https://user-images.githubusercontent.com/428897/119747396-9c03cd00-becd-11eb-9cd0-fae8f5e61389.png)

## Card popup
![localhost_3000_(iPhone X) - 2021-05-27T092458 199](https://user-images.githubusercontent.com/428897/119747400-9dcd9080-becd-11eb-8e19-00b2b715fbf7.png)

Need to connect user attributes to populate the view; last task

**Comment by Show-M** [comment]
1 correction needed...

The base of each peakflow calculation is **the highest peakflow of all time users recorded**.
Morning or Evening are not important.
Im sorry but i dont know how to pick "the highest peakflow of all time"

e.g 
```
on 注意ゾーン1
●ピークフローの値：  _______～_______　
（自己最良値の８０％～６０％）
```

Left should be ("highest-all-time"×0.8)
Right should be  ("highest-all-time"×0.6)

**Comment by rgagne** [comment]
oh.

Seems weird though. What if the user entered some really large number by accident?

**Comment by Show-M** [comment]
that counts...higher is better.
I mean if a super-big-number got added, it will be weird anyway.

**Comment by rgagne** [comment]
Some of them say 30%.. should they be N * .3?
