### ISSUE TITLE
Add text within icon field on the bottom of app

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#68]
You see texts in the very bottom of as-is. 
Texts for each from left to right are below.
①「トップ」　②「カレンダー」　③「薬」　④「資料」　⑤「アラーム」

![IMG_0231 2](https://user-images.githubusercontent.com/61481039/110459345-372ba880-8110-11eb-8ccb-f111149b0440.PNG)
![IMG_0230](https://user-images.githubusercontent.com/61481039/110459444-54f90d80-8110-11eb-9334-9f1ffaae594e.PNG)

**Comment by rgagne** [comment]
This has come up before. We don't support this.

**Comment by Show-M** [comment]
on hold as it is not really important.
