### ISSUE TITLE
Add message selections for alarm clock

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#93]
Scroll format
4 type of pop-up message: 
・お薬は服用しましたか？
・日記は入力しましたか？
・ピークフローはしましたか？
・何か忘れていませんか？

**Comment by rgagne** [comment]
are these randomly chosen?

**Comment by Show-M** [comment]
manually chosen.

**Comment by rgagne** [comment]
Sorry, was not clear with the question. The messages come from a script and can be set in the script. Currently a sentence in English. It can easily be updated to one of those phrases and/or a randomly selected phrase. We do not have a way for the user to pick one of the phrases and save it with the reminder.

Script:
```
-- Lua Code
local userId = param("userId")

log.info("Triggered for " .. userId)

core.SendPush({
    id=userId,
    title="Reminder",
    message="Please take your medicine"
})
```

**Comment by Show-M** [comment]
How about "user types in a message manually" ?

**Comment by Show-M** [comment]
Dr prefer 2nd option
