### ISSUE TITLE
Name for alarm clock should be provided automatically

### ISSUE THREAD

**Issue by Show-M** [weaveio/WOLL-General-forum#94]
# Goal

Currently name field is for manual input.  Dr would like to change it to pre-configured set of choices.

# Requirements

Extend MarkupTriggers.tsx and TriggerEdit.tsx to support either the current approach or for a pre-configured list of reminder names.

- [x] 1. Support an `entry` and `dropdown` fields as indicated below

   - `entry` = dropdown | text (default is text)
   - `dropdown` if entry is dropdown then this will populate the dropdown; when the item is selected the time will change to the time in the list, however the user can override it
   - maxCount - user can not add more than that number of entries

- [x] 3. Name is set to the name from the dropdown

- [x] 4. When editing again if the prior set name is not available in the dropdown.. add a new entry (in the dropdown) with the new name and time value; this is to handle cases where the list changes

- [x] 2. Update the documentation with the details

The following markup should result in drop downs for Morning, Lunch and Afternoon that preconfigure the time indicated. 
```
{
  "rows": [
    {
      "cols": [
        {
          "tile": "triggers",
          "opts": {
            "trigger": {
              "behaviorKind": "script",
              "behaviorId": "107d2337-37be-4198-8ee1-14eec29ba296",
              "triggerKind": "schedule",
              "status": "active",
              "maxCount": 3,
              "entry": "dropdown"
            },
            "dropdown": [
              {
                "name": "Morning",
                "time": "8:00"                
              },
              {
                "name": "Lunch",
                "time": "12:00"                
              },
              {
                "name": "Afternoon",
                "time": "15:00"                
              }
            ]
          },
          "title": "アラーム"
        }
      ]
    }
  ]
}
```

# Screens
Screens in ぜん快ちゃん for キッズ

https://user-images.githubusercontent.com/428897/118915575-301ee300-b968-11eb-9fde-624c7f7e4c66.png
https://user-images.githubusercontent.com/428897/118915577-31e8a680-b968-11eb-83d2-53e0c08cab3e.png

**Comment by rgagne** [comment]
latest build

**Comment by Show-M** [comment]
I can set the alarm. But the alarm does not seem to get triggered on manually set-time.
